"""Lattice of attractors/repellers and nontrivial Conley-Morse-graph derivations.

Pure-stdlib graph algorithms layered on the parsed
:class:`CMGDB.morse_graph_parser.MorseGraph`. No DSGRN or pychomp dependency:
the lattice machinery and the ``transitive_reduction`` primitive (which some
upstream utilities delegate to pychomp) are implemented here directly.

Conventions, matching CMGDB's Morse graph:

* Morse-graph edges point from a higher Morse set to a lower one, so the
  attractor (downset) generated by a node ``v`` is ``descendants[v]`` (which
  the :class:`MorseGraph` precomputes and which already contains ``v``).
* ``minimal`` Morse nodes are the sinks, i.e. the elementary attractors.
* Node labels emitted by ``CMGDB.PlotMorseGraph`` look like
  ``"v : (P0, P1, ...)"`` where the ``P_i`` are Conley-index polynomials; a node
  is *trivial* when every ``P_i`` is ``"0"``.
"""

from __future__ import annotations

__all__ = [
    "DerivedGraph",
    "transitive_closure",
    "transitive_reduction",
    "elementary_attractors",
    "lattice_of_attractors",
    "lattice_of_repellers",
    "nontrivial_cmgraph",
    "attractor_type",
]

from dataclasses import dataclass

from CMGDB.morse_graph_parser import MorseGraph

# Guard against the (worst-case exponential) attractor lattice blowing up on a
# Morse graph with many incomparable nodes.
_MAX_LATTICE = 100_000


@dataclass
class DerivedGraph:
    """A small directed graph derived from a :class:`MorseGraph`.

    Mirrors the ``(nodes, edges, labels)`` shape of ``MorseGraph`` so the same
    inspection/plotting helpers apply. For lattices, ``sets`` maps each vertex
    to the attractor/repeller it represents (a frozenset of Morse-node ids); for
    the nontrivial Conley-Morse graph ``sets`` is ``None`` and the node ids are
    the surviving original Morse-node ids.
    """

    nodes: list[int]
    edges: dict[int, list[int]]
    labels: dict[int, str]
    sets: dict[int, frozenset[int]] | None = None


def _topological_order(nodes, edges):
    nodeset = set(nodes)
    indeg = {n: 0 for n in nodes}
    for src in nodes:
        for d in edges.get(src, []):
            if d in nodeset:
                indeg[d] += 1
    ready = [n for n in nodes if indeg[n] == 0]
    order: list[int] = []
    while ready:
        n = ready.pop()
        order.append(n)
        for d in edges.get(n, []):
            if d not in nodeset:
                continue
            indeg[d] -= 1
            if indeg[d] == 0:
                ready.append(d)
    if len(order) != len(nodeset):
        # Cycle: not a DAG. Fall back to insertion order.
        return list(nodes)
    return order


def transitive_closure(nodes, edges):
    """Strict forward reachability: ``closure[u]`` = nodes reachable from ``u``.

    ``edges`` maps each node to an iterable of direct successors. ``u`` itself is
    excluded. Assumes a DAG.
    """
    order = _topological_order(nodes, edges)
    closure: dict[int, set[int]] = {}
    for n in reversed(order):
        reached: set[int] = set()
        for child in edges.get(n, []):
            if child not in closure:
                continue
            reached.add(child)
            reached |= closure[child]
        closure[n] = reached
    for n in nodes:
        closure.setdefault(n, set())
    return closure


def transitive_reduction(nodes, edges):
    """Hasse-diagram reduction of a DAG.

    Returns ``reduced[u]`` = the direct successors of ``u`` with every redundant
    (transitively implied) edge removed: edge ``(u, v)`` is dropped iff ``v`` is
    reachable from another successor ``w`` of ``u``.
    """
    closure = transitive_closure(nodes, edges)
    reduced: dict[int, set[int]] = {}
    for u in nodes:
        children = {c for c in edges.get(u, []) if c in closure}
        reduced[u] = {
            v
            for v in children
            if not any(v in closure[w] for w in children if w != v)
        }
    return reduced


def elementary_attractors(morse_graph: MorseGraph) -> set[frozenset[int]]:
    """Principal downsets ``{v} | descendants(v)`` for every node, plus ``{}``."""
    elem = {frozenset()}
    for v in morse_graph.nodes:
        elem.add(morse_graph.descendants[v])
    return elem


def _join_closure(principals) -> set[frozenset[int]]:
    """Close a set of principal down/up-sets under union (join)."""
    lattice = {frozenset()} | set(principals)
    changed = True
    while changed:
        changed = False
        current = list(lattice)
        for i in range(len(current)):
            for j in range(i + 1, len(current)):
                u = current[i] | current[j]
                if u not in lattice:
                    lattice.add(u)
                    changed = True
                    if len(lattice) > _MAX_LATTICE:
                        raise ValueError(
                            f"attractor/repeller lattice exceeds {_MAX_LATTICE} "
                            "elements; the Morse graph has too many incomparable "
                            "nodes for explicit lattice enumeration"
                        )
    return lattice


def _lattice_graph(principals) -> DerivedGraph:
    """Build the Hasse-diagram :class:`DerivedGraph` of a join-closed lattice."""
    elements = sorted(_join_closure(principals), key=lambda A: (len(A), sorted(A)))
    index = {A: i for i, A in enumerate(elements)}
    sets = {i: A for i, A in enumerate(elements)}
    labels = {
        i: ("{" + ", ".join(str(x) for x in sorted(A)) + "}") if A else "{ }"
        for i, A in enumerate(elements)
    }
    # Partial order: vertex of a superset points to vertices of its proper subsets.
    partial_order = {
        index[A]: {index[B] for B in elements if B != A and B.issubset(A)}
        for A in elements
    }
    reduced = transitive_reduction(list(range(len(elements))), partial_order)
    edges = {i: sorted(reduced[i]) for i in range(len(elements)) if reduced[i]}
    return DerivedGraph(nodes=list(range(len(elements))), edges=edges, labels=labels, sets=sets)


def lattice_of_attractors(morse_graph: MorseGraph) -> DerivedGraph:
    """Lattice of attractors (downsets) of the Morse graph as a Hasse diagram."""
    principals = [morse_graph.descendants[v] for v in morse_graph.nodes]
    return _lattice_graph(principals)


def _transpose(nodes, edges):
    t: dict[int, list[int]] = {n: [] for n in nodes}
    nodeset = set(nodes)
    for u in nodes:
        for v in edges.get(u, []):
            if v in nodeset:
                t[v].append(u)
    return t


def lattice_of_repellers(morse_graph: MorseGraph) -> DerivedGraph:
    """Lattice of repellers (upsets) of the Morse graph as a Hasse diagram."""
    transposed = _transpose(morse_graph.nodes, morse_graph.edges)
    closure = transitive_closure(morse_graph.nodes, transposed)
    principals = [frozenset({v} | closure[v]) for v in morse_graph.nodes]
    return _lattice_graph(principals)


def _conley_polynomials(label):
    """Extract the Conley-index polynomial list from a Morse-graph node label.

    Labels look like ``"v : (P0, P1, ...)"``. Returns the list of polynomial
    strings, or ``None`` if the label carries no Conley annotation.
    """
    if label is None:
        return None
    body = label.split(":", 1)[1] if ":" in label else label
    body = body.strip()
    if not (body.startswith("(") and body.endswith(")")):
        return None
    inner = body[1:-1].strip()
    return [] if inner == "" else [p.strip() for p in inner.split(",")]


def _is_trivial(morse_graph: MorseGraph, node: int) -> bool:
    polys = _conley_polynomials(morse_graph.labels.get(node))
    if polys is None:
        raise ValueError(
            f"Morse node {node} label {morse_graph.labels.get(node)!r} has no "
            "Conley-index annotation; nontrivial-graph / attractor-type "
            "computation requires a Conley Morse graph (CMGDB.PlotMorseGraph "
            "output with annotations)"
        )
    return all(p == "0" for p in polys)


def _conley_label(label) -> str:
    polys = _conley_polynomials(label)
    return "(" + ", ".join(polys) + ")" if polys else (label or "")


def nontrivial_cmgraph(morse_graph: MorseGraph) -> DerivedGraph:
    """Prune trivial-Conley-index Morse nodes and reduce to a Hasse diagram.

    Survivors keep the induced reachability order (so an edge survives even when
    its only path runs through pruned trivial nodes), transitively reduced.
    """
    survivors = [n for n in morse_graph.nodes if not _is_trivial(morse_graph, n)]
    survivor_set = set(survivors)
    induced = {
        u: {w for w in morse_graph.descendants[u] if w != u and w in survivor_set}
        for u in survivors
    }
    reduced = transitive_reduction(survivors, induced)
    edges = {u: sorted(reduced[u]) for u in survivors if reduced[u]}
    labels = {n: _conley_label(morse_graph.labels.get(n)) for n in survivors}
    return DerivedGraph(nodes=list(survivors), edges=edges, labels=labels, sets=None)


def _is_maximal(morse_graph: MorseGraph, v: int, attractor) -> bool:
    """A node is maximal in an attractor if no other member points to it."""
    return not any(
        u != v and v in morse_graph.edges.get(u, []) for u in attractor
    )


def attractor_type(morse_graph: MorseGraph, attractor) -> int:
    """Classify an attractor (a set of Morse nodes) by its maximal nodes.

    Returns ``0`` if any maximal node has a trivial Conley index, ``2`` if there
    is a single (nontrivial) maximal node, and ``1`` for several incomparable
    nontrivial maximal nodes.
    """
    attractor = set(attractor)
    maximal = [v for v in attractor if _is_maximal(morse_graph, v, attractor)]
    if any(_is_trivial(morse_graph, v) for v in maximal):
        return 0
    return 2 if len(maximal) == 1 else 1
